export type MediaSpec = {
  slug: string; buildingType: string; size: string; users: string; mood: string;
  architecture: string; keyZones: string[]; materials: string[]; lighting: string;
  heroPrompt: string; videoPrompt: string;
};

export type ProjectMediaKind = "hero" | "gallery-01" | "gallery-02" | "detail" | "floor-plan" | "poster";

export const projectMediaPaths: Record<string, Record<ProjectMediaKind, string>> = {
  "private-residence": { hero: "hero.png", "gallery-01": "hero.png", "gallery-02": "hero.png", detail: "hero.png", "floor-plan": "hero.png", poster: "hero.png" },
  "urban-residence": { hero: "hero.png", "gallery-01": "gallery-01.png", "gallery-02": "gallery-02.png", detail: "detail.png", "floor-plan": "floor-plan.png", poster: "hero.png" },
  "hospitality-lifestyle": { hero: "hero.png", "gallery-01": "gallery-01.png", "gallery-02": "gallery-02.png", detail: "detail.png", "floor-plan": "floor-plan.png", poster: "hero.png" },
  "signature-interior": { hero: "hero.png", "gallery-01": "gallery-01.png", "gallery-02": "hero.png", detail: "hero.png", "floor-plan": "floor-plan.png", poster: "hero.png" },
  "collaborative-hq": { hero: "hero.png", "gallery-01": "gallery-01.png", "gallery-02": "detail.png", detail: "detail.png", "floor-plan": "floor-plan.png", poster: "hero.png" },
  "innovation-campus": { hero: "hero.png", "gallery-01": "gallery-01.png", "gallery-02": "gallery-02.png", detail: "detail.png", "floor-plan": "floor-plan.png", poster: "hero.png" },
};

export const mediaSpecs: MediaSpec[] = [
  { slug:"private-residence", buildingType:"Premium urban private residence", size:"2,400–3,200 sq ft", users:"A multigenerational family of 4–6", mood:"Quiet, warm, tactile, deeply lived-in", architecture:"Layered apartment interior with filtered thresholds, a central light court and long visual axes", keyZones:["Arrival gallery","Living lounge","Dining court","Quiet study","Primary suite","Family threshold"], materials:["Warm limestone","Smoked oak","Hand-finished lime plaster","Antique brass","Textured linen"], lighting:"Soft morning daylight, warm concealed evening light, deep natural shadows", heroPrompt:"Cinematic editorial architectural photograph of a premium Mumbai residence, layered thresholds framing a sunlit living and dining court, warm limestone floor, smoked oak joinery, lime plaster walls, antique brass details, textured linen, Indian contemporary minimalism, calm human warmth, lived-in but uncluttered, 24mm architectural lens, eye level, soft Monday morning daylight, realistic materials, no people, no text, 16:9", videoPrompt:"10-second slow architectural dolly through a layered Mumbai residence from a shadowed arrival gallery into a sunlit living court, subtle curtain movement, shifting daylight across limestone, realistic interior film, stable camera, premium editorial grade, no people, no text, seamless ending" },
  { slug:"urban-residence", buildingType:"Adaptable compact city apartment", size:"1,200–1,800 sq ft", users:"Young creative family working partly from home", mood:"Precise, flexible, optimistic, calm", architecture:"Open apartment organised by a multifunctional joinery spine and sliding partitions", keyZones:["Convertible studio","Living room","Dining workspace","Children’s room","Hidden storage spine","Balcony garden"], materials:["Ash timber","Muted olive lacquer","Terrazzo","Brushed steel","Natural wool"], lighting:"Clear diffused daylight with crisp task lighting", heroPrompt:"High-end architectural editorial photograph of an adaptable Bengaluru apartment, movable olive partitions and ash timber storage spine transforming an open living room into work and family zones, terrazzo floor, brushed steel accents, soft balcony garden, precise contemporary Indian interior, diffused daylight, 28mm lens, realistic, no people, no text, 16:9", videoPrompt:"10-second cinematic transformation of a compact Bengaluru apartment, slow lateral camera as sliding panels reveal a concealed desk and shift living space into a focus studio, subtle daylight, realistic architectural visualization, refined neutral grade, no people, no text" },
  { slug:"hospitality-lifestyle", buildingType:"Boutique courtyard restaurant and lifestyle venue", size:"4,500–6,000 sq ft", users:"Guests gathering for slow dining and evening culture", mood:"Social, shaded, sensorial, relaxed", architecture:"Indoor-outdoor dining landscape arranged around planted courts and a single communal table", keyZones:["Arrival garden","Courtyard table","Intimate dining bays","Open kitchen","Bar threshold","Event terrace"], materials:["Local laterite","Oxidised copper","Dark teak","Handmade tile","Dense tropical planting"], lighting:"Dappled tropical daylight moving into amber evening pools", heroPrompt:"Cinematic architectural photograph of a boutique Goa courtyard restaurant, long communal table below a floating shaded canopy, laterite walls, dark teak, oxidised copper, handmade tile, lush tropical planting, dappled late afternoon light, hospitality interior with intimate dining bays, atmospheric yet refined, 24mm lens, photoreal, no people, no text, 16:9", videoPrompt:"12-second cinematic architectural film moving from a tropical arrival garden into a Goa courtyard restaurant, leaves casting moving shadows, copper and teak catching amber evening light, slow elegant gimbal move, empty before service, realistic, no people, no text" },
  { slug:"signature-interior", buildingType:"Private gallery and collectible interior", size:"1,800–2,500 sq ft", users:"Collector, guests and small cultural gatherings", mood:"Monastic, crafted, dramatic, intimate", architecture:"Sequence of mineral rooms calibrated around art, objects and negative space", keyZones:["Threshold chamber","Object gallery","Reading room","Listening room","Collector’s table","Sculpture court"], materials:["Mineral plaster","Blackened steel","Travertine","Dark walnut","Bronze mesh"], lighting:"Museum-grade directional light against deep ambient shadow", heroPrompt:"Editorial architectural photograph of a private collectible interior in Mumbai, monastic mineral plaster gallery with sculptural objects isolated in negative space, travertine plinths, blackened steel, dark walnut and bronze mesh, controlled museum lighting, deep shadows, cinematic composition, 35mm lens, photorealistic, no people, no text, 16:9", videoPrompt:"10-second museum-like tracking shot through a dark refined private gallery, directional pools of light reveal sculpture and crafted objects one by one, mineral plaster and bronze details, slow precise camera, dramatic but warm, no people, no text" },
  { slug:"collaborative-hq", buildingType:"Technology company headquarters", size:"35,000–55,000 sq ft across 3 levels", users:"350–500 hybrid product, design and business employees", mood:"Energetic, intelligent, human, hospitality-led", architecture:"A collaborative social core surrounded by team neighbourhoods and acoustic focus bands", keyZones:["Town hall stair","Social heart","Project rooms","Focus library","Hybrid meeting suites","Wellbeing terrace","Client forum"], materials:["Recycled aluminium","FSC oak","Acoustic felt","Low-carbon concrete","Muted olive textiles","Terracotta ceramic"], lighting:"Bright indirect daylight with warm social lighting and precise focus illumination", heroPrompt:"Award-level workplace architectural visualization of a Bengaluru technology headquarters, dramatic collaborative social core with amphitheatre stair, suspended meeting rooms and planted bridges, surrounded by quiet focus library, low-carbon concrete, FSC oak, recycled aluminium, olive acoustic felt and terracotta ceramic, hospitality warmth, diverse spatial scales, morning daylight, cinematic 20mm lens, photoreal, no logos, no text, 16:9", videoPrompt:"15-second cinematic workplace film entering a Bengaluru technology headquarters, camera glides through a double-height social heart, rises past an amphitheatre stair toward planted bridges and suspended collaboration rooms, screens show abstract light only, morning activity suggested through moving shadows but no visible people, architectural visualization, premium warm grade, no logos, no text" },
  { slug:"innovation-campus", buildingType:"Research, innovation and maker campus", size:"120,000–180,000 sq ft across multiple buildings", users:"800–1,200 researchers, engineers, makers and visiting partners", mood:"Future-facing, porous, ambitious, grounded", architecture:"A public learning street connects team houses, laboratories, maker halls and outdoor forums", keyZones:["Learning street","Maker hall","Prototype labs","Team houses","Forum steps","Material library","Rooftop test garden"], materials:["Exposed structural steel","Rammed earth","Translucent polycarbonate","Reclaimed timber","Stainless mesh","Native landscape"], lighting:"High daylight, glowing translucent volumes at dusk, precise technical light", heroPrompt:"Visually ambitious future innovation campus in Mumbai, vast public learning street connecting maker halls, research labs and team houses, exposed steel frames, rammed earth walls, translucent polycarbonate volumes, reclaimed timber, stainless mesh and native landscape, people-scaled despite large volume, late afternoon light, cinematic architectural visualization, 18mm lens, photoreal, no people, no logos, no text, 16:9", videoPrompt:"15-second cinematic fly-through at human eye level along a future Mumbai innovation campus learning street, maker hall doors open toward landscaped forums, translucent labs glow as daylight moves toward dusk, exposed steel and rammed earth, subtle kinetic façade panels, smooth camera, photoreal architectural film, no people, no logos, no text" },
];

export const mediaPath = (slug: string, file: string) => `/projects/${slug}/${file}`;

export const projectMediaPath = (slug: string, kind: ProjectMediaKind) =>
  mediaPath(slug, projectMediaPaths[slug]?.[kind] ?? "hero.png");
