"use client";
import Link from "next/link";
import Image from "next/image";
import { usePathname } from "next/navigation";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Expand, Menu, Pause, Play, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { projects } from "@/content/site";
import ProjectMedia from "./ProjectMedia";

const nav = [["Work", "/work"], ["Approach", "/approach"], ["Studio", "/studio"], ["Journal", "/journal"], ["Contact", "/contact"]];
const deck = [
  ["01", "Who we are", "Rooted in experience.\nRising into workplace design."], ["02", "Our philosophy", "Designing beyond\nstructures."],
  ["03", "What we design", "We design how\nspaces work."], ["04", "Our experience", "From homes\nto workplaces."],
  ["05", "Selected work", "Six studies.\nOne human lens."], ["06", "Workplace design", "People don’t experience\nfloor plans."],
  ["07", "Our approach", "Listen. Map.\nMake. Test."], ["08", "Design intelligence", "Evidence into\natmosphere."],
  ["09", "The team", "Different disciplines.\nShared curiosity."], ["10", "Why Root & Rise", "Design beyond\nthe photograph."],
  ["11", "Vision", "Room for people, ideas\nand businesses to grow."], ["12", "Let’s design", "What could your\nspace become?"],
] as const;

export default function Shell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const [menu, setMenu] = useState(false); const [present, setPresent] = useState(false); const [slide, setSlide] = useState(0); const [paused, setPaused] = useState(false); const lock = useRef(false); const touchX = useRef(0);
  const move = useCallback((n: number) => setSlide((s) => Math.max(0, Math.min(deck.length - 1, s + n))), []);
  useEffect(() => { setMenu(false); }, [path]);
  useEffect(() => { document.body.style.overflow = menu || present ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [menu, present]);
  useEffect(() => { const onKey = (e: KeyboardEvent) => { const editing = ["INPUT", "TEXTAREA", "SELECT"].includes((e.target as HTMLElement).tagName); if (!present && !editing && e.key.toLowerCase() === "p") return setPresent(true); if (!present) return; if (e.key === "Escape") setPresent(false); if (e.key === "ArrowRight") move(1); if (e.key === "ArrowLeft") move(-1); if (e.key === " ") { e.preventDefault(); setPaused((v) => !v); } if (/^[1-9]$/.test(e.key)) setSlide(Math.min(deck.length - 1, +e.key - 1)); }; addEventListener("keydown", onKey); return () => removeEventListener("keydown", onKey); }, [move, present]);
  const wheel = (e: React.WheelEvent) => { if (lock.current || Math.abs(e.deltaY) < 20) return; lock.current = true; move(e.deltaY > 0 ? 1 : -1); setTimeout(() => { lock.current = false; }, 600); };
  return <>
    <header className={`nav ${path === "/" ? "nav--home" : ""}`}><Link className="brand" href="/" aria-label="Root and Rise home"><i><Image src="/brand/logo.png" width={34} height={34} alt="" priority/></i><span>Root &amp; Rise<small>Design Studio</small></span></Link><nav>{nav.map(([label, href]) => <Link className={path === href ? "active" : ""} key={href} href={href}>{label}</Link>)}<button onClick={() => setPresent(true)}>Present <kbd>P</kbd></button><Link className="nav-cta" href="/contact">Start a conversation</Link></nav><button className="menu-button" aria-label="Open menu" onClick={() => setMenu(true)}><Menu /></button></header>
    <AnimatePresence>{menu && <motion.div className="mobile-menu" initial={{ clipPath: "inset(0 0 100% 0)" }} animate={{ clipPath: "inset(0)" }} exit={{ clipPath: "inset(0 0 100% 0)" }} transition={{ duration: .55, ease: [.16,1,.3,1] }}><button aria-label="Close menu" onClick={() => setMenu(false)}><X /></button><span>RR / Navigation</span>{nav.map(([label, href], i) => <motion.div key={href} initial={{ opacity: 0, x: -30 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .12 + i * .06 }}><Link href={href}>{label}</Link></motion.div>)}<button className="mobile-present" onClick={() => { setMenu(false); setPresent(true); }}>Enter presentation</button></motion.div>}</AnimatePresence>
    {children}
    <footer className="footer"><div><span>Root &amp; Rise</span><h2>What could your<br /><em>space become?</em></h2><Link href="/contact">Start a conversation <ArrowRight /></Link></div><div className="footer-meta"><span>Mumbai / Bengaluru</span><span>Designing beyond structures.</span><span>© {new Date().getFullYear()} Root &amp; Rise</span></div></footer>
    <AnimatePresence>{present && <motion.div className="deck" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onWheel={wheel} onTouchStart={e=>{touchX.current=e.touches[0].clientX}} onTouchEnd={e=>{const d=touchX.current-e.changedTouches[0].clientX;if(Math.abs(d)>45)move(d>0?1:-1)}}><div className="deck-grid"/><header><span>ROOT &amp; RISE / GUIDED TOUR</span><button aria-label="Exit presentation" onClick={() => setPresent(false)}><X /></button></header><AnimatePresence mode="wait"><motion.div className="deck-visual" key={`visual-${slide}`} initial={{ opacity:0,scale:1.08 }} animate={{ opacity:.72,scale:1 }} exit={{ opacity:0,scale:.96 }} transition={{duration:paused?0:.9,ease:[.16,1,.3,1]}}><ProjectMedia project={projects[Math.min(projects.length-1,Math.max(0,slide-3))]} kind={slide%3===0?"hero":slide%3===1?"gallery-02":"detail"} video={slide===4||slide===5}/></motion.div></AnimatePresence><div className="deck-slice"/><AnimatePresence mode="wait"><motion.main key={slide} initial={{ opacity: 0, x: 100, clipPath:"inset(0 100% 0 0)" }} animate={{ opacity: 1, x: 0, clipPath:"inset(0)" }} exit={{ opacity: 0, x: -100 }} transition={paused ? { duration: 0 } : { duration: .72, ease: [.16,1,.3,1] }}><span>{deck[slide][0]} / {deck[slide][1]}</span><h2>{deck[slide][2].split("\n").map((line) => <i key={line}>{line}</i>)}</h2><p>{["A design studio shaping meaningful residential, lifestyle and workplace environments.", "Spaces designed around people, purpose and possibility.", "Focus, collaboration, culture, comfort and growth.", "The context changes. The understanding of people remains.", "Four experience chapters and two workplace futures.", "They experience arrival, movement, conversation and pause.", "Human signals translated into spatial decisions.", "Behaviour and culture made visible through design.", "A collaborative practice shaped around the work.", "Beauty gets attention. Experience earns memory.", "To shape environments where people and businesses grow.", "Tell us about your space, your people and where you’re going."][slide]}</p></motion.main></AnimatePresence><footer><div className="deck-progress"><i style={{ width: `${(slide + 1) / deck.length * 100}%` }}/></div><span>{String(slide + 1).padStart(2,"0")} / 12</span><div><button disabled={slide === 0} aria-label="Previous" onClick={() => move(-1)}><ArrowLeft /></button><button aria-label={paused ? "Resume" : "Pause"} onClick={() => setPaused((v) => !v)}>{paused ? <Play/> : <Pause/>}</button><button aria-label="Fullscreen" onClick={() => document.documentElement.requestFullscreen?.()}><Expand/></button><button disabled={slide === 11} aria-label="Next" onClick={() => move(1)}><ArrowRight/></button></div></footer></motion.div>}</AnimatePresence>
  </>;
}
